# Generated by Django 3.1 on 2020-08-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='发布时间')),
                ('last_edit_date', models.DateTimeField(verbose_name='最后修改时间')),
            ],
        ),
    ]
